import { Injectable, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class AuditService {
  constructor(private prisma: PrismaService) {}

  async getLogs(userId: string, role: string, query: { tableName?: string; userId?: string }) {
    if (role === 'SUPER_ADMIN') {
      return this.prisma.auditLog.findMany({
        where: query,
        orderBy: { createdAt: 'desc' },
      });
    }

    if (role === 'HOSPITAL_ADMIN') {
      // Allow HOSPITAL_ADMIN to see all logs. In a more complex setup, you'd scope this
      // to only logs generated by staff working at their hospital.
      return this.prisma.auditLog.findMany({
        where: query,
        orderBy: { createdAt: 'desc' },
      });
    }

    throw new ForbiddenException('You do not have permission to view audit logs');
  }
}
