// backend/src/common/constants/role.enum.ts

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PHARMACY = 'PHARMACY',
  PATIENT = 'PATIENT',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  PHARMACIST = 'PHARMACIST',
  CASHIER = 'CASHIER',
  NURSE = 'NURSE',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  RECEPTIONIST = 'RECEPTIONIST',
  TECHNICIAN = 'TECHNICIAN',
}
